### ISSUE TITLE
Segfault in X11 mode [bug]

### ISSUE THREAD

**Issue by Wellidontcare** [B-LechCode/sooScreenShare#15]
The screenServer randomly crashes with a segfault.

I traced it back to XFixesGetCursorImage() in the grabMousePtr() function sometimes returning a nullptr. If this happens the program crashes.

Proposed fix:
Check if the pointer is a nullptr and return.

**Comment by B-LechCode** [comment]
Should have fixed it. Could you please check it?

**Comment by Wellidontcare** [comment]
I checked your code and it seems to fix the issue for me. (No crashes)

What bothers me a little is, that I've not been able to reproduce the bug with the old code. 

There are no hints in the Xfixes documentation on when the XfixesGetCursorImage function could return a nullpointer.
